=== ssjz99/ArxmlUtility/Autosar/AutosarXsd/Autosar/Config/dsdd_autosar_config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (C) 2009 dSPACE GmbH -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="DataDictionary">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Configuration" type="Configuration"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Configuration">
		<xs:sequence>
			<xs:element name="AUTOSAR" type="AUTOSAR"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AUTOSAR">
		<xs:sequence>
			<xs:element name="Settings">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="SupportedArVersions">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="ArVersion" maxOccurs="unbounded">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="AutosarVersion" type="_ArVersion"/>
												<xs:element name="Revision" type="xs:normalizedString"/>
												<xs:element name="SchemaFile" type="xs:normalizedString"/>
												<xs:element name="TransformationFileExport" type="xs:normalizedString" minOccurs="0"/>
												<xs:element name="TransformationFileImport" type="xs:normalizedString" minOccurs="0"/>
												<xs:element name="BaseTypeGenericFile" type="xs:normalizedString"/>
												<xs:element name="ImportTemplate" type="xs:normalizedString" minOccurs="0"/>
												<xs:element name="ExportTemplate" type="xs:normalizedString" minOccurs="0"/>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="NameTemplates">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="NameTemplate" type="KeyValuePair" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="KeyValuePair">
		<xs:attribute name="Key" type="xs:string"/>
		<xs:attribute name="Value" type="xs:string"/>
	</xs:complexType>
	<xs:simpleType name="_ArVersion" final="list">
		<xs:restriction base="xs:string">
			<xs:enumeration value="2.1"/>
			<xs:enumeration value="3.0"/>
			<xs:enumeration value="3.1"/>
			<xs:enumeration value="3.2"/>
			<xs:enumeration value="4.0"/>
			<xs:enumeration value="4.1"/>
			<xs:enumeration value="4.2"/>
			<xs:enumeration value="4.3"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="_PatternOnOff" final="list">
		<xs:restriction base="xs:string">
			<xs:enumeration value="On"/>
			<xs:enumeration value="Off"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="_ArExportStrategy" final="restriction">
		<xs:restriction base="xs:string">
			<xs:enumeration value="OneFileForAllPackages"/>
			<xs:enumeration value="OneFilePerPackage"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="_ArImportStrategy" final="restriction">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Merge"/>
			<xs:enumeration value="Overwrite"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== ssjz99/ArxmlUtility/Autosar/AutosarXsd/Autosar/Config/dsdd_autosar_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--======================================================================= -->
<!-- DSDD_CONFIG_AUTOSAR.XML                                                -->
<!--======================================================================= -->
<DataDictionary xsi:noNamespaceSchemaLocation="dsdd_autosar_config.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Configuration>
		<AUTOSAR>
			<Settings>
				<SupportedArVersions>
					<ArVersion>
						<AutosarVersion>2.1</AutosarVersion>
						<Revision>4</Revision>
						<SchemaFile>../2_1_4/autosar.xsd</SchemaFile>
						<BaseTypeGenericFile>../2_1_4/BaseTypeGeneric.arxml</BaseTypeGenericFile>
					</ArVersion>
					<ArVersion>
						<AutosarVersion>3.0</AutosarVersion>
						<Revision>2</Revision>
						<SchemaFile>../3_0_2/autosar.xsd</SchemaFile>
						<BaseTypeGenericFile>../3_0_2/BaseTypeGeneric.arxml</BaseTypeGenericFile>
					</ArVersion>
					<ArVersion>
						<AutosarVersion>3.0</AutosarVersion>
						<Revision>4</Revision>
						<SchemaFile>../3_0_4/autosar.xsd</SchemaFile>
						<BaseTypeGenericFile>../3_0_4/BaseTypeGeneric.arxml</BaseTypeGenericFile>
					</ArVersion>
					<ArVersion>
						<AutosarVersion>3.0</AutosarVersion>
						<Revision>6</Revision>
						<SchemaFile>../3_0_6/autosar.xsd</SchemaFile>
						<BaseTypeGenericFile>../3_0_6/BaseTypeGeneric.arxml</BaseTypeGenericFile>
					</ArVersion>
					<ArVersion>
						<AutosarVersion>3.0</AutosarVersion>
						<Revision>7</Revision>
						<SchemaFile>../3_0_7/autosar.xsd</SchemaFile>
						<BaseTypeGenericFile>../3_0_7/BaseTypeGeneric.arxml</BaseTypeGenericFile>
					</ArVersion>
					<ArVersion>
						<AutosarVersion>3.1</AutosarVersion>
						<Revision>0</Revision>
						<SchemaFile>../3_1_0/autosar.xsd</SchemaFile>
						<BaseTypeGenericFile>../3_1_0/BaseTypeGeneric.arxml</BaseTypeGenericFile>
					</ArVersion>
					<ArVersion>
						<AutosarVersion>3.1</AutosarVersion>
						<Revision>2</Revision>
						<SchemaFile>../3_1_2/autosar.xsd</SchemaFile>
						<BaseTypeGenericFile>../3_1_2/BaseTypeGeneric.arxml</BaseTypeGenericFile>
					</ArVersion>
					<ArVersion>
						<AutosarVersion>3.1</AutosarVersion>
						<Revision>4</Revision>
						<SchemaFile>../3_1_4/autosar.xsd</SchemaFile>
						<BaseTypeGenericFile>../3_1_4/BaseTypeGeneric.arxml</BaseTypeGenericFile>
					</ArVersion>
					<ArVersion>
						<AutosarVersion>3.1</AutosarVersion>
						<Revision>5</Revision>
						<SchemaFile>../3_1_5/autosar.xsd</SchemaFile>
						<BaseTypeGenericFile>../3_1_5/BaseTypeGeneric.arxml</BaseTypeGenericFile>
					</ArVersion>
					<ArVersion>
						<AutosarVersion>3.2</AutosarVersion>
						<Revision>1</Revision>
						<SchemaFile>../3_2_1/autosar.xsd</SchemaFile>
						<BaseTypeGenericFile>../3_2_1/BaseTypeGeneric.arxml</BaseTypeGenericFile>
					</ArVersion>
					<ArVersion>
						<AutosarVersion>3.2</AutosarVersion>
						<Revision>2</Revision>
						<SchemaFile>../3_2_2/autosar.xsd</SchemaFile>
						<BaseTypeGenericFile>../3_2_2/BaseTypeGeneric.arxml</BaseTypeGenericFile>
					</ArVersion>
					<ArVersion>
						<AutosarVersion>3.2</AutosarVersion>
						<Revision>3</Revision>
						<SchemaFile>../3_2_3/autosar.xsd</SchemaFile>
						<BaseTypeGenericFile>../3_2_3/BaseTypeGeneric.arxml</BaseTypeGenericFile>
					</ArVersion>
					<ArVersion>
						<AutosarVersion>4.0</AutosarVersion>
						<Revision>2</Revision>
						<SchemaFile>../4_0_2/AUTOSAR_4-0-2.xsd</SchemaFile>
						<TransformationFileExport>../4_0_2/ar422to402.xsl</TransformationFileExport>
						<BaseTypeGenericFile>../4_0_2/BaseTypeGeneric.arxml</BaseTypeGenericFile>
					</ArVersion>
					<ArVersion>
						<AutosarVersion>4.0</AutosarVersion>
						<Revision>3</Revision>
						<SchemaFile>../4_0_3/AUTOSAR_4-0-3.xsd</SchemaFile>
						<TransformationFileExport>../4_0_3/ar422to403.xsl</TransformationFileExport>
						<BaseTypeGenericFile>../4_0_3/BaseTypeGeneric.arxml</BaseTypeGenericFile>
					</ArVersion>
					<ArVersion>
						<AutosarVersion>4.1</AutosarVersion>
						<Revision>1</Revision>
						<SchemaFile>../4_1_1/AUTOSAR_4-1-1.xsd</SchemaFile>
						<TransformationFileExport>../4_1_1/ar422to411.xsl</TransformationFileExport>
						<BaseTypeGenericFile>../4_1_1/BaseTypeGeneric.arxml</BaseTypeGenericFile>
					</ArVersion>
					<ArVersion>
						<AutosarVersion>4.1</AutosarVersion>
						<Revision>2</Revision>
						<SchemaFile>../4_1_2/AUTOSAR_4-1-2.xsd</SchemaFile>
						<TransformationFileExport>../4_1_2/ar422to412.xsl</TransformationFileExport>
						<BaseTypeGenericFile>../4_1_2/BaseTypeGeneric.arxml</BaseTypeGenericFile>
					</ArVersion>
					<ArVersion>
						<AutosarVersion>4.1</AutosarVersion>
						<Revision>3</Revision>
						<SchemaFile>../4_1_3/AUTOSAR_4-1-3.xsd</SchemaFile>
						<TransformationFileExport>../4_1_3/ar422to413.xsl</TransformationFileExport>
						<BaseTypeGenericFile>../4_1_3/BaseTypeGeneric.arxml</BaseTypeGenericFile>
					</ArVersion>
					<ArVersion>
						<AutosarVersion>4.2</AutosarVersion>
						<Revision>1</Revision>
						<SchemaFile>../4_2_1/AUTOSAR_4-2-1.xsd</SchemaFile>
						<TransformationFileExport>../4_2_1/ar422to421.xsl</TransformationFileExport>
						<BaseTypeGenericFile>../4_2_1/BaseTypeGeneric.arxml</BaseTypeGenericFile>
					</ArVersion>
					<ArVersion>
						<AutosarVersion>4.2</AutosarVersion>
						<Revision>2</Revision>
						<SchemaFile>../4_2_2/AUTOSAR_4-2-2.xsd</SchemaFile>
						<BaseTypeGenericFile>../4_2_2/BaseTypeGeneric.arxml</BaseTypeGenericFile>
					</ArVersion>
					<ArVersion>
						<AutosarVersion>4.3</AutosarVersion>
						<Revision>0</Revision>
						<SchemaFile>../4_3_0/AUTOSAR_4-3-0.xsd</SchemaFile>
						<TransformationFileExport>../4_3_0/ar422to430.xsl</TransformationFileExport>
						<TransformationFileImport>../4_3_0/ar430to422.xsl</TransformationFileImport>
						<BaseTypeGenericFile>../4_3_0/BaseTypeGeneric.arxml</BaseTypeGenericFile>
					</ArVersion>
				</SupportedArVersions>
			</Settings>
			<NameTemplates>
				<!-- Example: <NameTemplate Key="INTERNAL-BEHAVIOR"  Value="IB_$(ItemName)"/>-->
			</NameTemplates>
		</AUTOSAR>
	</Configuration>
</DataDictionary>
